apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-jar
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1663878042706057373"
    kapp.k14s.io/association: v1.e0c1c09d6d780ef670050e3574ddfb4e
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-jar
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.5.4
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;canary/carto.run/Workload/hello-jar;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"hello","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1663878042706057373","kapp.k14s.io/association":"v1.e0c1c09d6d780ef670050e3574ddfb4e"},"name":"hello-jar","namespace":"canary"},"spec":{"params":[{"name":"gitops_repository_name","value":"trp-gitops-canary"},{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"source":{"image":"harbor.h2o-4-1396.h2o.vmware.com/tap/sc/java-jar@sha256:2d018a2f38d88ea8168e90cf4143432ab5c9f418eca775402a62c8c800b1e8dc"}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-jar
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        kapp.k14s.io/app: "1663878042706057373"
        kapp.k14s.io/association: v1.e0c1c09d6d780ef670050e3574ddfb4e
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: hello-jar
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.h2o-4-1396.h2o.vmware.com/jeff/sc/hello-jar-canary@sha256:e94ae9c3abddd23c40af900e9fa4dc67551ba678a3e9f2898c9ed683f5e8376b
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

