apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: csharp-weather
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1679864904293570532"
    kapp.k14s.io/association: v1.dd4611e25ca8a4c383f2c293d521348c
    app.kubernetes.io/component: run
    carto.run/workload-name: csharp-weather
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;workloads/carto.run/Workload/csharp-weather;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"hello","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1679864904293570532","kapp.k14s.io/association":"v1.dd4611e25ca8a4c383f2c293d521348c"},"name":"csharp-weather","namespace":"workloads"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_repository_name","value":"trp-gitops-canary"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/jeffellin/csharp-weather.git"}}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: csharp-weather
        kapp.k14s.io/app: "1679864904293570532"
        kapp.k14s.io/association: v1.dd4611e25ca8a4c383f2c293d521348c
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: csharp-weather
    spec:
      containers:
      - image: registry.gcp.ellin.net/tap/supply-chain/csharp-weather-workloads@sha256:3a79d11111651a7b097b43b1784c80881b76cb324ff57dca68ac07f8933a0868
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

